name: Publish NuGet package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Git Version
        id: version
        uses: codacy/git-version@2.2.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release
      - name: Pack
        run: dotnet pack --no-build --configuration Release -o . --include-symbols -p:SymbolPackageFormat=snupkg -p:Version=${{ steps.version.outputs.version }}
      - name: Publish
        run: dotnet nuget push *.nupkg --source https://apiint.nugettest.org/v3/index.json --api-key ${{secrets.NUGET_API_TOKEN}}
      - name: Create version tag
        run: git tag "${{ steps.version.outputs.version }}"
      - run: git push